IDEA-386055, debugger: fix thread dumps
Helper methods should explicitly list all classes to be loaded. Otherwise, NoClassDefFoundError occurs. So it's easier to get rid of extra classes.

^IDEA-386055

GitOrigin-RevId: 98bd23ec5e09a163f9df57f1993cb40c3f4144bb